-- Create table to store user push subscriptions
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  subscription jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, subscription)
);

-- Turn on RLS
alter table public.push_subscriptions enable row level security;

-- Allow users to insert their own subscriptions
create policy "Users can insert their own subscriptions"
  on public.push_subscriptions for insert
  with check (auth.uid() = user_id);

-- Allow users to read their own subscriptions (mainly for debugging)
create policy "Users can view their own subscriptions"
  on public.push_subscriptions for select
  using (auth.uid() = user_id);

-- Allow users to delete their own subscriptions
create policy "Users can delete their own subscriptions"
  on public.push_subscriptions for delete
  using (auth.uid() = user_id);

-- Service Role (Edge Function) needs full access
-- (Service role bypasses RLS by default, but good to know)
